###
POST http://127.0.0.1:5000/api/drives HTTP/1.1

### empty line!!!
POST http://127.0.0.1:5000/api/lists HTTP/1.1
Content-Type: application/json

{"op":"listdir", "to_drive":"D:/", "to_dir":""}

###
POST http://127.0.0.1:5000/api/listdetail HTTP/1.1
Content-Type: application/json

{"op":"listdetail", "to_drive":"D:/", "to_dir":"test"}